"""ToyShop SQLite storage layer."""

from toyshop.storage.database import (
    init_database,
    close_database,
    get_db,
    transaction,
    create_project,
    get_project,
    save_architecture_from_design,
    get_latest_snapshot,
)
from toyshop.storage.wiki import (
    WikiVersion,
    WikiTestSuite,
    VersionDiff,
    create_version,
    bind_git_commit,
    save_test_suite,
    get_version,
    get_version_by_commit,
    get_version_by_number,
    get_latest_version,
    list_versions,
    get_test_suite,
    diff_versions,
    log_event,
    get_changelog,
    extract_test_metadata,
)

__all__ = [
    "init_database",
    "close_database",
    "get_db",
    "transaction",
    "create_project",
    "get_project",
    "save_architecture_from_design",
    "get_latest_snapshot",
    # Wiki
    "WikiVersion",
    "WikiTestSuite",
    "VersionDiff",
    "create_version",
    "bind_git_commit",
    "save_test_suite",
    "get_version",
    "get_version_by_commit",
    "get_version_by_number",
    "get_latest_version",
    "list_versions",
    "get_test_suite",
    "diff_versions",
    "log_event",
    "get_changelog",
    "extract_test_metadata",
]
